name: Run UI or API Tests

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Which module to run'
        required: true
        default: 'ui'
        type: choice
        options:
          - ui
          - api
      browser:
        description: 'Which browser to run on'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - edge
          - firefox

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run ${{ github.event.inputs.module }} tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run UI Tests On ${{ github.event.inputs.browser }} browser
        if: ${{ github.event.inputs.module == 'ui' }}
        run: mvn -f ui-tests/pom.xml clean test -Dui.browser=${{ github.event.inputs.browser }} -Dheadless=true -Dui.standard.user=${{ secrets.STD_USER_NAME }} -Dui.valid.password=${{ secrets.STD_PASSWORD }} -Dui.locked.user=${{ secrets.LOCKED_USER_NAME }};

      - name: Run API Tests
        if: ${{ github.event.inputs.module == 'api' }}
        run: mvn -f api-tests/pom.xml clean test -Dapi.key=${{ secrets.VALID_API_KEY }};

      - name: Generate Allure Report
        run: |
          mkdir -p allure-report
          mvn -f ${{ github.event.inputs.module }}-tests/pom.xml allure:report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ${{ github.event.inputs.module }}-tests/target/site/allure-maven-plugin

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.event.inputs.module }}-tests/target/site/allure-maven-plugin
          destination_dir: ${{ github.event.inputs.module }}

      - name: Add Summary with Report Link
        run: |
          echo "## âœ… ${{ github.event.inputs.module }} Test Run Summary" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸ§ª Module: \`${{ github.event.inputs.module }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸŒ Browser: \`${{ github.event.inputs.browser }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- ðŸ“Š [View Allure Report](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ github.event.inputs.module }}/index.html)" >> $GITHUB_STEP_SUMMARY
